import * as XLSX from 'xlsx';
import { DailyODRecord } from '../types/od';

export const sanitizeFileName = (str: string): string => {
  return str.replace(/[^a-zA-Z0-9_-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
};

export const formatDateDisplay = (dateStr: string): string => {
  try {
    const parts = dateStr.split('-');
    if (parts.length === 3) {
      // YYYY-MM-DD -> DD-MM-YYYY
      return `${parts[2]}-${parts[1]}-${parts[0]}`;
    }
  } catch {
    // fallback
  }
  return dateStr;
};

export const exportDailyODExcel = (
  date: string,
  workName: string,
  records: DailyODRecord[]
) => {
  const formattedDate = formatDateDisplay(date);
  const odCount = records.filter(r => r.status === 'OD').length;
  const absentCount = records.filter(r => r.status === 'Absent').length;
  const total = records.length;

  // Build 2D Sheet Data
  const sheetData: (string | number)[][] = [
    ['TARAS 2K26 — ECE DEPARTMENT'],
    ['DAILY ON DUTY (OD) REPORT'],
    [''],
    ['Date:', formattedDate, '', 'Department:', 'ECE'],
    ['Work / Event:', workName, '', 'Total Students:', total],
    ['Summary:', `OD: ${odCount}`, `Absent: ${absentCount}`, '', ''],
    [''],
    ['S.No', 'Student Name', 'Register Number', 'Section', 'Year', 'Role / Designation', 'OD / Absent', 'Event / Work', 'Date'],
  ];

  // Add Student Rows — sorted by Register Number for official submission
  const sorted = [...records].sort((a, b) => a.registerNumber.localeCompare(b.registerNumber));
  sorted.forEach((record, index) => {
    sheetData.push([
      index + 1,
      record.studentName,
      record.registerNumber,
      `Section ${record.section}`,
      `Year ${record.year}`,
      (record as any).role || 'Student',
      record.status,
      record.workName || workName,
      formattedDate,
    ]);
  });

  // Add Summary footer
  sheetData.push(['']);
  sheetData.push(['TOTAL ON DUTY (OD):', odCount, '', 'TOTAL ABSENT:', absentCount, '', 'TOTAL:', total]);
  sheetData.push(['Report Generated by TARAS President on:', new Date().toLocaleString('en-GB')]);
  sheetData.push(['Submitted to: Class Advisor / EOT Staff']);

  // Create Worksheet
  const ws = XLSX.utils.aoa_to_sheet(sheetData);

  // Set column widths for clean readability
  ws['!cols'] = [
    { wch: 6 },  // S.No
    { wch: 25 }, // Student Name
    { wch: 16 }, // Register Number
    { wch: 11 }, // Section
    { wch: 9 },  // Year
    { wch: 18 }, // Role / Designation
    { wch: 14 }, // OD / Absent
    { wch: 26 }, // Event / Work
    { wch: 14 }, // Date
  ];

  // Create Workbook
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Daily OD Report');

  // Generate Filename
  const safeWork = sanitizeFileName(workName || 'Work');
  const filename = `TARAS_OD_${formattedDate}_${safeWork}.xlsx`;

  // Trigger real .xlsx download
  XLSX.writeFile(wb, filename);
};
